loglevel: Debug
WriteDirectory: test_output
AWS:
  access_key: access
  secret_key: supersecret
  session_key: ""
  region: us-east-1
raids:
  rds:
    config:
      instance_identifier: unique-id-name
      database: test
      primary_region: us-east-1
      host: localhost
      password: password
      port: 3306
      user: root
    tactics:
      - CCC-Taxonomy