loglevel: Debug
WriteDirectory: test_output
raids:
  RDS:
    config:
      aws_access_key: access_key
      aws_secret_key: supersecret
      aws_session_key: ""
      aws_region: region
      aws_db_instance_identifier: instance_identifier    
      database: test
      host: localhost
      password: password
      port: 3306
      user: root
    tactics:
      - CCC-Taxonomy