loglevel: Debug
WriteDirectory: test_output
raids:
  RDS:
    config:
      database: test
      host: localhost
      password: password
      port: 3306
      user: root
    tactics:
      - CCC-Taxonomy